---
 - name: ctf package manager sotfware
   apt: name={{ item }} state=present
   with_items:
      - manpages-ja
      - manpages-ja-dev
      - gcc
      - gdb
      - build-essential
      - gcc-multilib
      - strace
      - ltrace
      - sharutils
      - binutils
      - john
      - socat
      - hydra
      - tcpdump
      - nmap

 - name: pyenv build version 3.5.1
   command: su - {{ login_user }} -c "pyenv install 3.5.1"
   args:
    creates: /home/{{ login_user }}/.pyenv/versions/3.5.1

 - name: python 3.5.1を全体に適用する
   command: su - {{ login_user }} -c "pyenv global 3.5.1"

 - name: install sqlmap
   git: repo=https://github.com/sqlmapproject/sqlmap.git  dest=/home/{{ login_user }}/local/sqlmap

 - name: chown sqlmap
   file: path=/home/{{ login_user }}/local/sqlmap recurse=yes owner={{ login_user }} group={{ login_user }}

 - name: install sslscan
   git: repo=https://github.com/rbsec/sslscan/ dest=/home/{{ login_user }}/local/sslscan/

 - name: chown sslscan
   file: path=/home/{{ login_user }}/local/sslscan recurse=yes owner={{ login_user }} group={{ login_user }}

 - name: build sslscan
   command: su - {{ login_user }} -c "cd /home/{{ login_user }}/local/sslscan/ && make static"
   args:
    chdir: /home/{{ login_user }}/local/sslscan/
    creates: /home/{{ login_user }}/local/sslscan/sslscan

 - name: build sslscan
   command: sh -c "cd /home/{{ login_user }}/local/sslscan/ && make install"
   args:
    chdir: /home/{{ login_user }}/local/sslscan/
    creates: /usr/bin/sslscan

 - name: install radare2
   git: repo=https://github.com/radare/radare2 dest=/home/{{ login_user }}/local/radare2/

 - name: chown radare2 
   file: path=/home/{{ login_user }}/local/radare2 recurse=yes owner={{ login_user }} group={{ login_user }}

 - name: build radare2
   command: su - {{ login_user }} -c "cd /home/{{ login_user }}/local/radare2/ && sudo sys/install.sh"
   args:
    chdir: /home/{{ login_user }}/local/radare2/
    creates: /usr/bin/radare2
 
 - name: install peda
   git: repo=https://github.com/zachriggle/peda dest=/home/{{ login_user }}/local/peda/

 - name: create .gdbinit
   file: path=/home/{{ login_user }}/.gdbinit owner={{ login_user }} group={{ login_user }} mode=0644 state=touch

 - name: setting peda to .gdbinit
   lineinfile:
    dest='/home/{{ login_user }}/.gdbinit'
    state=present
    line='source /home/{{ login_user }}/local/peda/peda.py'

 - name: setting intel syntac .gdbinit
   lineinfile:
    dest='/home/{{ login_user }}/.gdbinit'
    state=present
    line='set disassembly-flavor intel'

 - name: install rp++
   command: su - {{ login_user }} -c "wget https://github.com/downloads/0vercl0k/rp/rp-lin-x64 -O /home/{{ login_user }}/local/bin/rp"
   args:
    creates: /home/{{ login_user }}/local/bin/rp

 - name: chmod rp
   file: path=/home/{{ login_user }}/local/bin/rp owner={{ login_user }} group={{ login_user }} mode=700

 - name: install checksec.sh
   command: su - {{ login_user }} -c "wget https://github.com/slimm609/checksec.sh/archive/1.6.tar.gz -O /tmp/1.6.tar.gz"
   args:
    creates: /home/{{login_user}}/local/bin/checksec

 - name: decompress checksec.sh  
   command: su - {{ login_user }} -c "cd /tmp/ && tar zxvf /tmp/1.6.tar.gz"
   args:
    creates: /home/{{login_user}}/local/bin/checksec

 - name: move checksec.sh
   command: su - {{ login_user }} -c "mv /tmp/checksec.sh-1.6/checksec /home/{{login_user}}/local/bin/checksec"
   args:
    creates: /home/{{login_user}}/local/bin/checksec

 - name: chmod checksec.sh
   file: path=/home/{{ login_user }}/local/bin/checksec owner={{ login_user }} group={{ login_user }} mode=700

 - name: download pkcrack
   command: su - {{ login_user }} -c "wget -O /home/{{ login_user }}/local/pkcrack-1.2.2.tar.gz https://www.unix-ag.uni-kl.de/~conrad/krypto/pkcrack/pkcrack-1.2.2.tar.gz"
   args:
    creates: /home/{{ login_user }}/local/pkcrack-1.2.2.tar.gz


